Task 1-> Creating Arrays
1. Write a Python program to:
i. Create a 1D NumPy array of 10 integers ranging from 1 to 10.

In [1]:
import numpy as np
arr1=np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


ii. Create a 2D NumPy array of shape (3, 3) with integers from 1
to 9?

In [2]:
arr2=np.arange(1,10).reshape(3,3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


iii. Create a 3D NumPy array with random floating-point numbers
of shape (3, 5, 3)?

In [3]:
arr3=np.random.rand(3,5,3)
print(arr3)

[[[0.01131142 0.19471496 0.96825808]
  [0.16268103 0.58660874 0.66538746]
  [0.74996019 0.52923851 0.0328556 ]
  [0.42031793 0.530691   0.43148926]
  [0.45987031 0.98960424 0.57602951]]

 [[0.29270575 0.55967295 0.64614382]
  [0.30198146 0.71187756 0.37224803]
  [0.32948231 0.050123   0.46010526]
  [0.10774958 0.92045616 0.6352533 ]
  [0.37300618 0.2565621  0.46652874]]

 [[0.26462708 0.4565455  0.06706433]
  [0.86266785 0.37093373 0.11488235]
  [0.49325367 0.40277883 0.34961567]
  [0.21581648 0.88994597 0.35615816]
  [0.47627401 0.03753201 0.74228806]]]


2. Display the shape, size, and datatype of each array.

In [7]:
def display(array):
    print(f"Shape: {array.shape}")
    print(f"Size: {array.size}")
    print(f"Datatype: {array.dtype}")

display(arr1)
display(arr2)
display(arr3)

Shape: (10,)
Size: 10
Datatype: int64
Shape: (3, 3)
Size: 9
Datatype: int64
Shape: (3, 5, 3)
Size: 45
Datatype: float64


Task 2-> Array Indexing and Slicing
1. Create a NumPy array from the following list:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [8]:
data=[10, 20, 30, 40, 50, 60, 70, 80, 90]
arr=np.array(data)
print(arr)

[10 20 30 40 50 60 70 80 90]


2. Write a Python program to:
3. Perform the above operations and display the results
i. Retrieve the first three elements of the array.

In [9]:
print(arr[:3])

[10 20 30]


ii. Retrieve every alternate element of the array.

In [10]:
print(arr[::2])

[10 30 50 70 90]


iii. Reverse the array.


In [11]:
print(arr[::-1])

[90 80 70 60 50 40 30 20 10]


Task 3-> Mathematical Operations
1. Create two NumPy arrays, A and B, each with 5 random integers
between 1 and 20.


In [13]:
A=np.random.randint(1,21,5)
B=np.random.randint(1,21,5)
print(A)
print(B)

[14  1  8  6 11]
[ 1  4 19 16  2]


2. Write a Python program to:
i. Add, subtract, multiply, and divide the two arrays elementwise.


In [14]:
print("\nAddition:", A + B)
print("Subtraction:", A - B)
print("Multiplication:", A * B)
print("Division:", A / B)


Addition: [15  5 27 22 13]
Subtraction: [ 13  -3 -11 -10   9]
Multiplication: [ 14   4 152  96  22]
Division: [14.          0.25        0.42105263  0.375       5.5       ]


ii. Compute the dot product of the arrays.

In [15]:
DotProduct=np.dot(A,B)
print(DotProduct)

288


iii. Find the mean, median, standard deviation, and variance of
array A.

In [16]:
print(np.mean(A))
print(np.median(A))
print(np.std(A))
print(np.var(A))

8.0
8.0
4.427188724235731
19.6


iv. Identify the maximum and minimum values in array B and
their indices.

In [17]:
print(np.max(B),np.argmax(B))
print(np.min(B),np.argmin(B))

19 2
1 0


Task 4-> Reshaping and Transposing
1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.

In [18]:
arr=np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


2. Write a Python program to:
i. Reshape the array into a 2D array of shape (4, 3).

In [19]:
arr2=np.arange(1,13).reshape(4,3)
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


ii. Reshape the array into a 3D array of shape (2, 2, 3).

In [20]:
arr3=np.arange(1,13).reshape(2,2,3)
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


iii. Transpose the reshaped 2D array and display its shape.

In [21]:
arr2=np.arange(1,13).reshape(4,3).T
print(arr2)

print(arr2.shape)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
(3, 4)


Task 5-> Boolean Masking and Filtering
1. Create a NumPy array with 15 random integers between 10 and 50.

In [22]:
arr=np.random.randint(10,51,15)
print(arr)

[25 42 45 49 22 27 35 18 49 43 29 30 34 23 14]


2. Write a Python program to:
i. Find all elements greater than 25.

In [23]:
print(arr[arr>25])

[42 45 49 27 35 49 43 29 30 34]


ii. Replace all elements less than 30 with 0.

In [24]:
arr2=arr.copy()
arr2[arr2<30]=0
print(arr2)

[ 0 42 45 49  0  0 35  0 49 43  0 30 34  0  0]


iii. Count the number of elements divisible by 5.

In [25]:
count=arr[(arr%5==0)&(arr!=0)]
print(count)
print(count.size)

[25 45 35 30]
4


Task 6-> Working with Built-in Functions
1. Use NumPy's built-in functions to:
i. Create an array of 10 equally spaced values between 0 and 1.

In [26]:
arr=np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


ii. Create an identity matrix of size 4x4.

In [27]:
arr2=np.eye(4)
print(arr2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


iii. Generate a 1D array of 20 random integers between 1 and 100,
sort it, and find the 5 largest elements.

In [29]:
arr3=np.random.randint(1,101,20)
print(arr3)
sorted=np.sort(arr3)
print(sorted)
print(sorted[-5:])

[ 57  79  49  56  82  11   5  86  65  34  44  47  64 100  25  57   8  44
  92  65]
[  5   8  11  25  34  44  44  47  49  56  57  57  64  65  65  79  82  86
  92 100]
[ 79  82  86  92 100]


Task 7-> Generic
1. Create a Python program that:
i. Generates two large random arrays of size (100, 100).
ii. Performs matrix multiplication on the two arrays.
iii. Finds the determinant and inverse of the resulting matrix (if
possible).
iv. Measures the time taken to complete these operations.

In [31]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import time

#Two random arrays.
A = np.random.rand(100, 100)    
B = np.random.rand(100, 100)


start_time = time.time()
product = np.dot(A, B)  

 #Matix Multiplication
Multiplication_time=time.time()-start_time
print("The product of matrix is: ",product)
print(f"Matrix Multiplication is completed in {Multiplication_time:.4f} seconds.")
print()

start_time = time.time()

#Determinant of Matrix.
det=np.linalg.det(product)      
Determinant_time=time.time()-start_time
print("The Determinant of matrix is: ",det)
print(f"Time taken to calculate determinant is {Determinant_time:.4f} seconds")
print()

if np.isclose(det, 0):
    print("The Matrix is singular and cannot be inverted.")
else:
    start_time=time.time()

    #Inverse of Matrix.
    inverse=np.linalg.inv(product)      
    Inverse_time=time.time()-start_time
    print("The inverse of matrix is: ",inverse)
    print(f"Time taken to calculate Inverse is {Inverse_time:.4f} seconds")
    print()




The product of matrix is:  [[19.96686579 22.68934071 22.30651384 ... 23.02394085 25.41672338
  24.81947836]
 [20.68808791 22.5967209  21.26585524 ... 22.29355571 24.22328648
  25.81657305]
 [23.16257785 24.59818271 24.01188825 ... 25.00069411 24.73334241
  27.47635747]
 ...
 [23.58444794 25.3960149  24.34942976 ... 26.14660393 28.54283717
  27.61299228]
 [21.71890901 23.48638985 22.47976262 ... 24.09503614 26.62470176
  27.2027663 ]
 [22.88185613 24.78619875 22.62198361 ... 25.47408218 27.22020269
  29.05436717]]
Matrix Multiplication is completed in 0.0005 seconds.

The Determinant of matrix is:  2.966373648363399e+50
Time taken to calculate determinant is 0.0003 seconds

The inverse of matrix is:  [[ 1.13989183  0.17773254  0.42885178 ... -1.57040198  1.32144492
  -0.1355969 ]
 [ 0.21880063 -0.23336564  0.77400138 ... -1.01217474  1.65051828
   0.27975596]
 [ 3.429642    1.35347498 -0.47644685 ... -1.32077298  1.12751015
   0.30234477]
 ...
 [ 1.09704254  0.4090544   0.51147716 ... -